language: scala
scala:
   - 2.10.6
   - 2.10.5
   - 2.10.4
   - 2.10.3
   - 2.10.2
   - 2.10.1
   - 2.9.3
   - 2.9.2
jdk:
  - openjdk7
  - oraclejdk8
script:
   - cd stratagem
   - sbt ++$TRAVIS_SCALA_VERSION test
